// AI-powered nutritional analysis card.
//
// ## Layout
// ┌──────────────────────────────────────┐
// │ [gradient]   Smart Analysis          │
// │ [icon box]   You're nearing your…    │
// └──────────────────────────────────────┘
//
// The icon container uses a [LinearGradient] that blends the secondary
// and primary theme colours.  `Image.asset` with the `color` parameter
// tints the PNG white, which works well over the gradient background.
//
// ## When to use Row + Expanded
// When you have a fixed-width element (the icon) next to text that
// should fill the remaining space, wrap the text side in [Expanded].
// Without [Expanded], the text column would try to take its intrinsic
// width, potentially causing overflow on narrow screens.
import 'package:flutter/material.dart';

import '../../../core/constants/app_dimensions.dart';

/// Displays a personalised dietary recommendation generated by the
/// AI engine, accompanied by a gradient sparkle icon.
class SmartAnalysisCard extends StatelessWidget {
  /// Recommendation body text.
  ///
  /// In production this comes from [AiController]; for now the
  /// dashboard hard-codes a placeholder string.
  final String text;

  const SmartAnalysisCard({
    super.key,
    required this.text,
  });

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final tt     = Theme.of(context).textTheme;
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      padding: const EdgeInsets.all(AppDimensions.paddingMD),
      decoration: BoxDecoration(
        // Same card surface treatment as every other dashboard card
        color: isDark ? const Color(0xFF1A2236) : Colors.white,
        borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
        boxShadow: isDark
            ? null
            : [
                BoxShadow(
                  color: Colors.black.withAlpha(13),
                  blurRadius: 10,
                  offset: const Offset(0, 2),
                ),
              ],
      ),
      child: Row(
        // `crossAxisAlignment: start` aligns the icon to the top of
        // the text column instead of vertically centering it.
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Gradient icon container ──────────────────────────────────
          // [LinearGradient] flows from secondary → primary
          // (purple → teal in light mode) to create a vibrant accent.
          Container(
            width: 44,
            height: 44,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [scheme.secondary, scheme.primary],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(AppDimensions.radiusMD),
            ),
            child: Center(
              // `color: Colors.white` on Image.asset applies a colour
              // filter that paints every non-transparent pixel white.
              // This is handy for single-colour icons over coloured
              // backgrounds.
              child: Image.asset(
                'assets/images/sparks.png',
                width: 22,
                height: 22,
                color: Colors.white,
              ),
            ),
          ),

          const SizedBox(width: 14),

          // ── Title + analysis body ───────────────────────────────────
          // [Expanded] tells the Column to fill whatever horizontal
          // space the Row has left after the icon + SizedBox.
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Card heading
                Text(
                  'Smart Analysis',
                  style: tt.bodyLarge?.copyWith(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 6),
                // AI recommendation text.
                // `height: 1.4` increases line spacing for readability.
                Text(
                  text,
                  style: tt.bodySmall?.copyWith(height: 1.4),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
