// Section header that labels a group of meals by date.
//
// ## Presentation-only widget
// This widget has zero logic — it receives pre-computed data and
// renders it.  Keeping widgets "dumb" like this makes them easy to
// test, reuse, and reason about.  All business logic (date grouping,
// calorie summing) lives in [MealController].
//
// ## Layout
// A simple [Row] with [MainAxisAlignment.spaceBetween] pushes the
// date label to the left edge and the calorie total to the right.
import 'package:flutter/material.dart';

/// Renders a date label (left) and aggregated calorie count (right)
/// above a section of meal cards in the history list.
class DateSectionHeader extends StatelessWidget {
  /// Human-readable date label (e.g. "Today", "Yesterday", "Mon, Apr 10").
  /// Generated by [MealController.groupedHistory].
  final String label;

  /// Sum of kilocalories for every meal in this section.
  /// Calculated in the history screen's `_buildItem` method using
  /// `fold<int>` over the section's meal list.
  final int totalCalories;

  const DateSectionHeader({
    super.key,
    required this.label,
    required this.totalCalories,
  });

  @override
  Widget build(BuildContext context) {
    final tt = Theme.of(context).textTheme;

    return Padding(
      // Top padding separates this header from the section above;
      // bottom padding creates space before the first meal card.
      padding: const EdgeInsets.only(top: 8, bottom: 12),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          // Bold date label — uses headlineMedium from the theme so
          // it matches the "Daily Log" heading on the dashboard.
          Text(
            label,
            style: tt.headlineMedium?.copyWith(fontWeight: FontWeight.bold),
          ),
          // Muted calorie total — bodySmall keeps it secondary to the
          // date label, establishing a clear visual hierarchy.
          Text(
            '${_formatNumber(totalCalories)} kcal total',
            style: tt.bodySmall,
          ),
        ],
      ),
    );
  }

  /// Inserts a comma as a thousands separator (e.g. 1420 → "1,420").
  ///
  /// `~/` is Dart's integer division (floors the result).
  /// `padLeft(3, '0')` ensures the remainder is always 3 digits.
  static String _formatNumber(int n) {
    if (n >= 1000) {
      return '${n ~/ 1000},${(n % 1000).toString().padLeft(3, '0')}';
    }
    return '$n';
  }
}
